services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatWorkAppChatBundle\Command\:
    resource: '../../Command/'
  WechatWorkAppChatBundle\Controller\:
    resource: '../../Controller/'
  WechatWorkAppChatBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatWorkAppChatBundle\Repository\:
    resource: '../../Repository/'
  WechatWorkAppChatBundle\Service\:
    resource: '../../Service/'
